// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        return linux;
      default:
        return android;
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCzvSmn2A_kSLrDfA3frRzj2WWwFs7p3VQ',
    appId: '1:536165799568:web:d57bd180486fd4f319ea15',
    messagingSenderId: '536165799568',
    projectId: 'loan-bazaar-3a60b',
    authDomain: 'loan-bazaar-3a60b.firebaseapp.com',
    storageBucket: 'loan-bazaar-3a60b.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDTvEc7OaY9rleEeG10ZGCNZpLGgnToJgk',
    appId: '1:536165799568:android:7395514b976028f919ea15',
    messagingSenderId: '536165799568',
    projectId: 'loan-bazaar-3a60b',
    storageBucket: 'loan-bazaar-3a60b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDTvEc7OaY9rleEeG10ZGCNZpLGgnToJgk',
    appId: '1:536165799568:android:7395514b976028f919ea15',
    messagingSenderId: '536165799568',
    projectId: 'loan-bazaar-3a60b',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDTvEc7OaY9rleEeG10ZGCNZpLGgnToJgk',
    appId: '1:536165799568:android:7395514b976028f919ea15',
    messagingSenderId: '536165799568',
    projectId: 'loan-bazaar-3a60b',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCzvSmn2A_kSLrDfA3frRzj2WWwFs7p3VQ',
    appId: '1:536165799568:web:d57bd180486fd4f319ea15',
    messagingSenderId: '536165799568',
    projectId: 'loan-bazaar-3a60b',
  );

  static const FirebaseOptions linux = FirebaseOptions(
    apiKey: 'AIzaSyCzvSmn2A_kSLrDfA3frRzj2WWwFs7p3VQ',
    appId: '1:536165799568:web:d57bd180486fd4f319ea15',
    messagingSenderId: '536165799568',
    projectId: 'loan-bazaar-3a60b',
  );
}
